db:
  image: postgres:9.4.5
  environment:
    POSTGRES_USER: postgre
    POSTGRES_PASSWORD: '${DBPASS}'
  ports:
    - '5432:5432'
  volumes:
    - warmer-postgres:/var/lib/postgresql/data

redis:
  image: redis:3.0.5
  ports:
    - '6379:6379'
  volumes:
    - warmer-redis:/var/lib/redis/data

warmer:
  image: renatomenegasso/site-warmer
  links:
    - db
    - redis
  environment:
    DB: 'postgresql://postgre:${DBPASS}@db:5432/warmer?encoding=utf8&pool=5&timeout=5000'
    SLACK_TOKEN: '${SLACK_TOKEN}'
    SITEMAP: '${SITEMAP}'
    JOB_WORKER_URL: redis://redis:6379/0
    RAILS_ENV: production
