default: &default
  adapter: postgresql
  encoding: utf8

development:
  <<: *default
  url: postgresql://127.0.0.1/ws_development?user=dev&password=dev

test:
  <<: *default
  url: postgresql://localhost/ws_test?user=dev&password=dev

production:
  <<: *default
  url: <%= ENV['DB'] %>

wordpress: &wordpress
  adapter: mysql2
  encoding: utf8

wordpress_development:
  <<: *wordpress
  host: localhost
  database: wordpress_db
  username: root
  password:

wordpress_test:
  <<: *wordpress
  host: localhost
  database: wordpress_test
  username: root
  password:

wordpress_production:
  <<: *wordpress
  host: <%= ENV['WP_DB_HOST'] %>
  database: <%= ENV['WP_DB_SCHEMA'] %>
  username: <%= ENV['WP_DB_USER'] %>
  password: <%= ENV['WP_DB_PASS'] %>
