default: &default
  adapter: postgresql
  encoding: utf8

development:
  <<: *default
  url: postgresql://127.0.0.1/ws_development?user=dev&password=dev

test:
  <<: *default
  url: postgresql://localhost/ws_test?user=dev&password=dev

production:
  <<: *default
  url: <%= ENV['DB'] %>
