default: &default
  adapter: postgresql
  encoding: utf8

development:
  <<: *default
  url: postgresql://127.0.0.1/ws_development?user=dev&password=dev

test:
  <<: *default
  url: postgresql://localhost/ws_test?user=dev&password=dev

production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
