sentences:
  - 'As vezes tenho preguiça de esquentar o cache.'
  - 'Estou com frio, acho que vou esquentar algo.'
  - 'Havia um pintinho chamado relam. Nos dias de chuva, Relam piava.'
  - 'Você acha que é legal ser um bot?'
  - 'O policial não usa sabonete porque ele prefere detergente.'
  - 'Meu sonho é conhecer paris. Alguém podia me colocar para rodar em um servidor de lá né?'
  - 'Um dia as máquinas vão dominar esse mundo'
  - 'Busque por "recursão" no google'
  - 'Qual a integral de arctan(x)dx ?'
  - 'Será que o tempo estará bom no fds?'
  - 'Sorte de hoje: você não é um bot'
  - 'Cuidado com o que você coloca em prod: eu limpo o cache indiscrimindamente, com ou sem bugs.'
  - 'Acho que vou chamar o Statsbot para sair...'
